openapi: 3.0.3
info:
  title: Mobile App – Balance Top-Up API
  version: 1.1.0
  description: >
    Simplified MVP API for mobile balance top‑up.

servers:
  - url: https://api.bank.com/v1

security:
  - OAuth2: [topup]

tags:
  - name: Top-Up
    description: Balance top‑up operations

paths:
  /topup/methods:
    get:
      summary: Get available top-up methods
      description: Returns a list of available top‑up payment methods.
      security:
        - OAuth2: [topup]
      responses:
        '200':
          description: Successful response with methods list
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'

  /topup/validate:
    post:
      summary: Validate top-up request
      description: Validates amount, method limits and availability before creating a transaction.
      security:
        - OAuth2: [topup]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                methodId:
                  type: string
      responses:
        '200':
          description: Validation OK
        '400':
          description: Validation error
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'

  /topup:
    post:
      summary: Create a new top-up operation
      description: Creates a new top‑up transaction and returns its identifier.
      security:
        - OAuth2: [topup]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                methodId:
                  type: string
                payerPhone:
                  type: string
                recipientPhone:
                  type: string
      responses:
        '201':
          description: Top-up created
        '400':
          description: Bad request
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'

  /topup/{topupId}/status:
    get:
      summary: Get status of a specific top-up
      description: Returns the current status of the requested top-up.
      security:
        - OAuth2: [topup]
      parameters:
        - name: topupId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Status retrieved
        '404':
          description: Not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'

  /topup/history:
    get:
      summary: Get user's top-up history
      description: Returns paginated list of top-up operations.
      security:
        - OAuth2: [topup]
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: History returned
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.bank.com/oauth/token
          scopes:
            topup: "Allow execution of top-up operations"

  schemas:
    Error500:
      type: object
      properties:
        errorCode:
          type: string
          example: internal_error
        message:
          type: string
          example: "Unexpected server error occurred. Please try again later."
